name: JsHarmonyTutorials Screenhot Tests

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-screenshots:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [18.x, 20.x, 22.x]
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps: 
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm' # requires a package lock checked in
    - uses: mfinelli/setup-imagemagick@v7
    - run: magick
    - run: identify
      #- name: Disable AppArmor for puppeteer sandboxing
      #run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      #- run: cp test/test-screenshots-config/* ./
      #- run: npm install-test
