name: JsHarmonyTutorials Screenhot Tests Windows

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-screenshots:

    runs-on: windows-latest

    steps: 
    #- uses: actions/checkout@v4
    #- name: Use Node.js 22.x
    #uses: actions/setup-node@v4
    #with:
    #node-version: 22.x
        # cache: 'npm' # requires a package lock checked in
    - run: choco install -y imagemagick -PackageParameters LegacySupport=true
    - run: magick identify
    #- run: copy test\test-screenshots-config\* .\
    #- run: npm install-test
