# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: JsHarmonyTutorials Screenhot Tests

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-screenshots:

    runs-on: windows-latest

    strategy:
      matrix:
        #node-version: [18.x, 20.x, 22.x]
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create tutorial shell
      run: |
        mkdir jsh-tutorial-shell
        cd jsh-tutorial-shell
        npx jsharmony-cli create tutorials
    - name: Modify config file
      run: (gc app.config.local.js) -replace 'image-sharp', 'image-magick' -replace '//configTutorials', 'configTutorials' |Out-File 'app.config.local.js' -encoding ASCII
      shell: pwsh
    - run: npm run test-screenshots
